<div class="col-md-3 block">
    <h3>Siguenos</h3> 
    <ul class="rsosiales">
        <li><a class="facebook" title="facebook" href="https://www.facebook.com/pages/Casa-de-manos-y-pies/270025679844632?ref=profile">facebook</a></li>
        <li><a class="tweeter" title="tweeter" href="https://twitter.com/casademanosypie">Tweeter</a></li>
        <li><a class="google" title="google" href="https://plus.google.com/u/0/103549457749791105268/posts">google</a></li>
        <li><a class="youtube" title="youtube" href="">youtube</a></li>
    </ul>
    <?php print Html::img("colage.jpg", NULL, "width='250px'") ?>
</div>