<div id="informacion">
<h3>
	¿Quienes Somos?
</h3>
<p>
	Somos una empresa orientada al cuidado  e higiene de manos y pies, tratamiento preventivo de cáncer en la piel   con un alto personal calificado y certificado.
</p>
<p>
	Nuestro servicio incluye la atención a personas con problemas de diabetes.
</p>
	
	<blockquote>
	<h3>
	Visión
</h3>
	<p>Atención calificada y compromiso con responsabilidad a nuestros clientes.</p>
</blockquote>

<blockquote>
<h3>
	Misión
</h3>
	<p>Ser la clínica líder a nivel nacional en el cuidado de manos y pies con un alto compromiso de responsabilidad con nuestros clientes.</p>
</blockquote>
</div>


