<p> <?php print Html::img("manicure1.jpg", NULL, "style='float:left; width:35%; margin:0 15px 15px 0;'") ?> Una manicura es un tratamiento cosmético de la belleza para las uñas y las manos realizadas en casa o en un salón de uñas. Una manicura consiste en la presentación, la conformación del borde libre, empujando (con empujador de la cutícula) y recorte (con pinzas de la cutícula) cualquier tejido no vivo (limitado a cutícula y padrastros) de la placa de la uña, tratamientos, masajes de la mano y la aplicación de pulir. Cuando se aplica a las uñas de los pies y los pies, este tratamiento se conoce como una pedicura.</p>
<p>
	Algunos manicura pueden incluir la pintura de cuadros o diseños en las uñas o la aplicación de pequeñas calcomanías o joyas de imitación. Otros tratamientos para las uñas pueden incluir la aplicación de geles de uñas artificiales, consejos, o acrílicos, algunos de los cuales son referidos como manicuras francesas
</p>
<p>
	En muchas áreas, manicuristas tienen licencia y siguen la regulación. Dado que la piel es manipulada y, a veces se corta, hay un cierto riesgo de propagación de la infección cuando se utilizan las herramientas a través de muchas personas y, por tanto, el saneamiento es un problema grave.
</p>
<h3>
	Historia
</h3>
<p>
	Manicuras comenzaron hace 5.000 años. La manicura francesa se pueden hacer con las uñas artificiales, las cuales están diseñadas para parecerse a los naturales, y se caracterizan por la falta de color base, o las uñas de color rosa de bases naturales con puntas blancas. Las puntas de las uñas están pintadas de blanco, mientras que el resto de las uñas se pulen en una rosa o un tono nude adecuado. Sin embargo, también es más común hacer una manicura francesa en uñas naturales. Manicuras francesas pueden tener su origen en el siglo 18 de París y eran populares en los años 1920 y 1930.
</p>