<p>
	<?php print Html::img("pedicure1.jpg", NULL, "style='float:left; width:35%; margin:0 15px 15px 0;'") ?> Una pedicura es una manera de mejorar la apariencia de los pies y de las uñas. Proporciona un servicio similar a una manicura. La palabra se refiere a la pedicura superficiales tratamiento cosmético de los pies y las uñas de los pies. Un pedicure puede ayudar a prevenir enfermedades de las uñas y las alteraciones de las uñas. Arreglos de los pies se hacen para fines cosméticos, terapéuticos y médicos. Son muy populares en todo el mundo, sobre todo entre las mujeres. 
</p>
<p>
	Arreglos de los pies no se limita sólo a las uñas; células de la piel generalmente muertos en la planta de los pies se frotan apagado utilizando una piedra en bruto llamado una piedra pómez. Además, la atención de la pierna debajo de la rodilla se convirtió en un servicio común y ahora se espera incluir en pedicuras. Cuidado Pierna incluye depilación a través de cualquiera de afeitar o encerar seguido de una exfoliación granular, aplicación de cremas hidratantes, y un breve masaje en las piernas.
</p>

<h3>
	Historia
</h3>

<p>
	La gente ha estado pedicura las uñas por más de 4.000 años. En el sur de Babilonia, nobles usaron herramientas de oro macizo para darse manicuras y pedicuras. El uso de esmalte de uñas se remonta aún más lejos. Se originó en China en el año 3000 antes de Cristo, el color de uñas indica el estatus social, según un manuscrito de la dinastía Ming; uñas reales fueron pintados de negro y rojo. Los antiguos egipcios fueron Manicure todo el camino de vuelta a 2300 antes de Cristo. 
</p>
<p>
	Una representación de los primeros manicuras y pedicuras se encontró en un grabado de la tumba de un faraón y los egipcios eran conocidos por prestar especial atención a sus pies y piernas. Los egipcios también de color las uñas, utilizando rojo para mostrar la más alta clase social. Se dice que las uñas de Cleopatra estaban pintadas de un color rojo oscuro, mientras que la reina Nefertiti fue con un tono rubí llamativo. En el antiguo Egipto y Roma, los comandantes militares también se pintaban las uñas para que coincida con sus labios antes de ir a la batalla.
</p>