<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="">
        <title><?php print $SiteName ?></title>

        <!-- Bootstrap core CSS -->
        <?php Tag::css('bootstrap.min') ?>
        <?php Tag::css('bootstrap-theme.min') ?>
        <?php Tag::css('estilos') ?>
        <?php echo Html::includeCss() ?>
        
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <?php print Tag::js("backbone/underscore")?>
        <?php print Tag::js("backbone/backbone")?>
        <?php print Tag::js("scripts")?>

        <!-- Custom styles for this template -->
        <style>body{padding-top:50px;}.starter-template{padding:35px 15px;text-align:center;}</style>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <div id="bg_pattern">
            <?php View::partial("bootstrap/navbar", FALSE, array('status' => $status, 'SiteName' => $SiteName)) ?>


            <div class="headeshow">
                <div class="container">
                    <div id="inner-headeshow">
                        <h1>Casa de Manos y Píes</h1>
                        <h3>Pedicure y Manicure Profesional</h3>
                    </div>
                </div>    
            </div>
            <div class="container">
                <div class="starter-template">
                    <div class="conten">
                        <div class="row">
                     
                            <div class="<?php print $classes ?>">   
                                
                                <?php if (isset($title)): ?>
                                    <h3 class="page-title"><?php print $title ?></h3>
                                <?php endif ?>
                                
                                <?php View::content(); ?>
                            </div>
							
                            <?php if (isset($sidebar)): ?>
                                <?php if(isset($redes)):?>
                                    <?php View::partial("bootstrap/redes"); ?>
                                <?php endif; ?>
                            <?php endif ?>                            
                    
                        </div>
                    </div>
                </div>
            </div>
            
            <div id="footer">
                <div class="container">
                    <div class="col-md-12">
                        <?php View::partial("bootstrap/direccion") ?>
                    </div>
                </div>    
            </div>
        
        </div>
    </body>
</html>
<?php print Tag::js("bootstrap")?>